### ISSUE TITLE
exchange 'es' is impossible.

### ISSUE THREAD

**Issue by tankf33der** [SymbolicSoft/noiseexplorer#23]
**FYI.** While testing [Monokex](https://github.com/LoupVaillant/Monokex) against explorer I've found patterns which passed on explorer, but failed in monokex.
```
Bad protocol: mike2: Exchange 'es' is impossible.
mike2:
-> s
...
-> e
<- e,ee,es,se,s
```

**Comment by kaepora** [comment]
This seems to be a bug in Monokex. Your pattern, `mike2`, seems valid to me. It passes both the Noise Protocol Framework and Noise Explorer's pattern validity rules.

Monokex is processing the tokens in that pattern incorrectly. If you move the `s` token in the last message to occur before `es`, then your pattern works fine in Monokex.

Monokex is assuming that the order in which tokens appear in the same message matters, which is incorrect.

**Comment by LoupVaillant** [comment]
> *Monokex is assuming that the order in which tokens appear in the same message matters, which is incorrect.*

Okay, the state machine processes the token in a particular and very well defined order, is that right? Then the only way the order of tokens doesn't mater is because they are **sorted** before you give them to the state machine.

Right?

Because if sorting didn't happen, then the following 4 protocols wouldn't be equivalent:

1. `<- s ... -> e, es, s, ss`  -- IK (encrypt static key)
2. `<- s ... -> s, ss, e, es`  -- (encrypt ephemeral key)
3. `<- s ... -> e, s, es, ss`  -- encrypt no key at all
4. `<- s ... -> es, ss, e, s`  -- impossible (exchanges happen before the keys are known)

Clearly, there's a canonical order. But I've never heard of such a thing. What are the sorting rules?
