### ISSUE TITLE
Remove rs in patterns without remote static keys

### ISSUE THREAD

**Issue by kaepora** [SymbolicSoft/noiseexplorer#25]

**Comment by georgio** [comment]
This has been dealt with.

**Comment by burdges** [comment]
I've missed this somewhere since `xx::noisesession::NoiseSession::init_session` still has an `rs: PublicKey` argument, which I presume is the remote's public key.  A priori, I'd think an XX handshake should never know the public key when calling `init_session`, as otherwise another handshake should be used.  I suppose it's tricky because some protocols need an `rs` on one or the other side, but not both.
